### ISSUE TITLE
Support OpenAI compatible API using ChatOpenAI

### ISSUE THREAD

**Issue by Anddd7** [ahonn/logseq-plugin-ai-assistant#10]
Thanks for this awesome plugin~

I just want to configure some OpenAI compatible model via API, but i found most of them are using `/v1/chat/completions` which is wrapped as `ChatOpenAI` in langchain. e.g.

- ollama
- lingyiwanwu
- kimi (moonshot)

Maybe change to use ChatOpenAI can help this

```
  const model = new ChatOpenAI(
    {
      model: modelName,
      apiKey,
      streaming: false,
    },
    {
      basePath,
    }
  );
```

**Comment by Anddd7** [comment]
I forked a demo https://github.com/ahonn/logseq-plugin-ai-assistant/compare/master...Anddd7:logseq-plugin-ai-assistant:master?diff=split&w=

**Comment by ahonn** [comment]
Look great! Could you please raise a PR for this? I would be happy to merge.
