### ISSUE TITLE
Add specific tags based on the PromptOutputType

### ISSUE THREAD

**Issue by aforank** [ahonn/logseq-plugin-ai-assistant#2]
I would recommend to add tags based on the PromptOutputType type. 

- If the PromptOutputType is replace, then add tag to same block. (Current behavior in all cases)
- If the PromptOutputType is insert, then add tag to created block instead.

Also, if there is no tag specified in the settings, then do not add any tag. Currently it still adds a # even if the tags list is empty.

**Comment by ahonn** [comment]
Thank you for your feedback, your suggestions are very useful.

**Comment by ahonn** [comment]
Now, the behavior of tag when PromptOutputType is set to replace or insert has been fixed.

**Comment by aforank** [comment]
It works! Thanks a lot
