### ISSUE TITLE
adding a custom prompt results in Settings schema Error! 

### ISSUE THREAD

**Issue by tdeffieux** [ahonn/logseq-plugin-ai-assistant#5]
Hello, 

While trying to add a custom prompt by editing the logseq-plugin-ai-assistant.json file to add a custom prompt as described in the Readme :

```
 {
  "apiKey": "MyKey",
  "basePath": "https://api.openai.com/v1",
  "model": "gpt-3.5-turbo",
  "customPrompts": {
    "enable": true, // <- Make sure to enable this.
    "prompts": [
      {
        "name": "Markdown Table",
        "prompt": "Please generate a {{text}} Markdown table",
        "output": "replace" // "property", "replace" or "insert"
      }
    ]
  },
  "disabled": false
}
```

The plugin can not be used anymore and logseq now displays a "Settings schema Error! " when trying to configure the plugin.
Reverting to  "prompts": [ ] fixes the error.

Logeq version 0.9.17

Thanks for you help,

**Comment by ahonn** [comment]
I just tried it, and it's always working.
Make sure you have removed the comments in the JSON file, such as `// <- Make sure to enable this.`.

```json
 {
  "apiKey": "MyKey",
  "basePath": "https://api.openai.com/v1",
  "model": "gpt-3.5-turbo",
  "customPrompts": {
    "enable": true,
    "prompts": [
      {
        "name": "Markdown Table",
        "prompt": "Please generate a {{text}} Markdown table",
        "output": "replace"
      }
    ]
  },
  "disabled": false
}
```
