### ISSUE TITLE
Support for local models

### ISSUE THREAD

**Issue by KhazAkar** [ahonn/logseq-plugin-ai-assistant#7]
Hi!
Your plugin looks great and I'd want to use it, but does it support locally running models? If yes, how can I use them?

**Comment by ahonn** [comment]
Thanks for your feedback.
Not currently supported, I can add this feature if needed. Does configuring the URL of the local model in the plugin satisfy this requirement ?

If not, let me know how you'd like to use it and I'll be happy to support.

**Comment by KhazAkar** [comment]
I think it should satisfy the need if locally running OpenAI compatible server would be used by specifying it's address.
