### ISSUE TITLE
Readme Link broken

### ISSUE THREAD

**Issue by davidak** [ahonn/logseq-plugin-ai-assistant#8]
This link in the Readme is broken:

>See all built-in prompts [here](https://github.com/ahonn/logseq-plugin-ai-assistant/blob/master/src/preset.ts)

A good link seem to be https://github.com/ahonn/logseq-plugin-ai-assistant/tree/master/src/prompts now.

**Comment by ahonn** [comment]
Fixed. Thanks for your feedback.
